//! Widget integration tests - split into modules by widget type

mod accordion;
mod aistream;
mod alert;
mod autocomplete;
mod avatar;
mod badge;
pub mod canvas;
pub mod code_editor_tests;
pub mod collapsible;
pub mod color_picker;
pub mod combobox;
pub mod combobox_tests;
pub mod command_palette;
pub mod data_chart_tests;
pub mod datagrid;
pub mod datetime_picker;
pub mod debug_overlay;
pub mod digits;
pub mod divider;
pub mod display;
pub mod empty_state;
pub mod feedback;
pub mod filepicker;
pub mod filetree;
pub mod form_tests;
pub mod gauge;
pub mod heatmap_tests;
pub mod httpclient;
pub mod image;
pub mod input;
pub mod link;
pub mod list;
pub mod log_viewer_tests;
pub mod macros;
pub mod markdown;
pub mod masked_input;
pub mod masked_input_tests;
pub mod option_list;
pub mod pagination;
pub mod presentation;
pub mod progress;
pub mod qrcode;
pub mod radio;
pub mod range_picker;
pub mod rating;
pub mod resizable;
pub mod richlog;
pub mod richtext;
pub mod search_bar;
pub mod screen;
pub mod scroll;
pub mod select;
pub mod selection_list;
pub mod sidebar_tests;
pub mod skeleton;
pub mod slider;
pub mod slides;
pub mod spinner;
pub mod splitter;
pub mod statusbar;
pub mod stepper;
pub mod streamline;
pub mod switch;
pub mod syntax;
pub mod tabs;
pub mod terminal;
pub mod text;
pub mod textarea;
pub mod theme_picker;
pub mod timeline;
pub mod timer;
pub mod timeseries_tests;
pub mod tooltip;
pub mod traits;
pub mod transition;
pub mod validation;
pub mod vim;
pub mod waveline;
pub mod zen;
mod breadcrumb;
mod button;
mod calendar;
mod callout;
mod candlechart;
mod card;
mod checkbox;
mod code_editor;
mod code_editor_tests;
mod collapsible;
mod color_picker;
mod combobox;
mod combobox_tests;
mod command_palette;
mod data_chart_tests;
mod datagrid;
mod datetime_picker;
mod debug_overlay;
#[cfg(feature = "diff")]
mod diff;
mod digits;
mod divider;
mod empty_state;
mod filepicker;
mod filetree;
mod gauge;
mod heatmap_tests;
mod httpclient;
#[cfg(feature = "image")]
mod image;
mod input;
mod link;
mod list;
mod log_viewer_tests;
#[cfg(feature = "markdown")]
mod markdown;
mod masked_input;
mod form_tests;
mod masked_input_tests;
mod option_list;
mod pagination;
mod presentation;
mod markdown;
mod masked_input;
mod form_tests;
mod masked_input_tests;
mod option_list;
mod presentation;
mod progress;
#[cfg(feature = "qrcode")]
mod qrcode;
mod radio;
mod range_picker;
mod rating;
mod resizable;
mod richlog;
mod richtext;
mod search_bar;
mod screen;
mod scroll;
mod select;
mod selection_list;
mod sidebar_tests;
mod skeleton;
mod slider;
#[cfg(feature = "markdown")]
mod slides;
mod spinner;
mod splitter;
mod statusbar;
mod stepper;
mod streamline;
mod switch;
mod syntax;
mod tabs;
mod terminal;
mod text;
mod textarea;
mod theme_picker;
mod timeline;
mod timer;
mod timeseries_tests;
mod tooltip;
mod transition;
mod validation;
mod vim;
mod waveline;
mod zen;
