//! Widget integration tests - split into modules by widget type

mod accordion;
mod aistream;
mod alert;
mod autocomplete;
mod avatar;
mod badge;
pub mod breadcrumb;
mod button;
mod calendar;
mod callout;
mod candlechart;
mod card;
pub mod canvas;
mod checkbox;
pub mod code_editor_tests;
pub mod collapsible;
mod color_picker;
mod combobox;
pub mod combobox_tests;
pub mod command_palette_unit;
mod command_palette;
pub mod data;
pub mod data_chart_tests;
mod datagrid;
mod datetime_picker;
pub mod dropzone;
mod debug_overlay;
#[cfg(feature = "diff")]
mod diff;
mod digits;
mod divider;
mod display;
mod empty_state;
pub mod feedback;
mod filepicker;
mod filetree;
pub mod form; // New: rich_text_editor tests
mod form_tests;
mod gauge;
pub mod heatmap_tests;
pub mod httpclient;
pub mod multi_select;
#[cfg(feature = "image")]
mod image;
mod input;
mod link;
mod layout;
mod list;
mod log_viewer_tests;
#[cfg(feature = "markdown")]
mod markdown;
mod masked_input;
mod masked_input_tests;
mod mermaid;
mod option_list;
mod pagination;
mod pipeline;
mod placeholder;
mod points;
mod presentation;
mod progress;
#[cfg(feature = "sysinfo")]
mod procmon;
mod qrcode;
mod radio;
mod range_picker;
mod rating;
mod resizable;
mod richlog;
mod richtext;
mod search_bar;
pub mod screen;
pub mod sortable;
mod scroll;
mod scroll;
mod select;
mod selection_list;
mod sidebar_tests;
mod skeleton;
mod slider;
#[cfg(feature = "markdown")]
mod slides;
mod spinner;
mod splitter;
mod statusbar;
mod stepper;
mod streamline;
mod switch;
mod syntax;
mod tabs;
mod terminal;
#[cfg(feature = "syntax-highlighting")]
mod tree_sitter_highlight;
mod terminal_ansi;
mod terminal_types;
mod text;
mod textarea;
mod theme_picker;
mod timeline;
mod timer;
pub mod timeseries_tests;
mod tooltip;
mod transition;
mod validation;
mod vim;
mod waveline;
mod zen;
