//! Widget integration tests - split into modules by widget type

mod accordion;
mod aistream;
mod alert;
mod autocomplete;
mod avatar;
mod badge;
pub mod display;
pub mod feedback;
pub mod traits;
pub mod canvas;
mod breadcrumb;
mod button;
mod calendar;
mod callout;
mod candlechart;
mod card;
mod checkbox;
mod code_editor;
mod code_editor_tests;
mod collapsible;
mod color_picker;
mod combobox;
mod combobox_tests;
mod command_palette;
mod data_chart_tests;
mod datagrid;
mod datetime_picker;
mod debug_overlay;
#[cfg(feature = "diff")]
mod diff;
mod digits;
mod divider;
mod empty_state;
mod filepicker;
mod filetree;
mod gauge;
mod heatmap_tests;
mod httpclient;
#[cfg(feature = "image")]
mod image;
mod input;
mod link;
mod list;
mod log_viewer_tests;
#[cfg(feature = "markdown")]
mod markdown;
mod masked_input;
mod form_tests;
mod masked_input_tests;
mod option_list;
mod pagination;
mod presentation;
mod markdown;
mod masked_input;
mod form_tests;
mod masked_input_tests;
mod option_list;
mod presentation;
mod progress;
#[cfg(feature = "qrcode")]
mod qrcode;
mod radio;
mod range_picker;
mod rating;
mod resizable;
mod richlog;
mod richtext;
mod search_bar;
mod screen;
mod scroll;
mod select;
mod selection_list;
mod sidebar_tests;
mod skeleton;
mod slider;
#[cfg(feature = "markdown")]
mod slides;
mod spinner;
mod splitter;
mod statusbar;
mod stepper;
mod streamline;
mod switch;
mod syntax;
mod tabs;
mod terminal;
mod text;
mod textarea;
mod theme_picker;
mod timeline;
mod timer;
mod timeseries_tests;
mod tooltip;
mod transition;
mod validation;
mod vim;
mod waveline;
mod zen;
