name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting! Please search [existing issues](https://github.com/hawk90/revue/issues) first.

  - type: dropdown
    id: type
    attributes:
      label: Bug Type
      options:
        - Widget rendering
        - Layout/styling
        - Reactivity/state
        - Input handling
        - Performance
        - Crash/panic
        - Build error
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug and what you expected instead
      placeholder: |
        The button doesn't respond to Enter key.
        Expected: Should trigger on_click when Enter is pressed.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Create a button with on_click
        2. Focus the button
        3. Press Enter
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Example
      description: Minimal code to reproduce (optional but helpful)
      render: rust

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Version info and system details
      value: |
        - Revue:
        - Rust:
        - OS:
        - Terminal:
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
      description: Error messages, stack traces, or screenshots (optional)

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I searched existing issues
          required: true
