name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the suggestion! Please search [existing issues](https://github.com/hawk90/revue/issues) first.

  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - New Widget
        - Widget Enhancement
        - Styling/CSS
        - Layout
        - Reactivity
        - Animation
        - Performance
        - Developer Experience
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this solve?
      placeholder: |
        When building dashboards, I need to display real-time charts.
        Currently I have to manually manage redraws which is error-prone.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
      placeholder: |
        Add a Chart widget that re-renders when data changes.
        Support line, bar, and area charts with configurable colors.
    validations:
      required: true

  - type: textarea
    id: api
    attributes:
      label: API Example
      description: Show how you'd use this feature (optional)
      placeholder: |
        let data = signal(vec![10.0, 20.0, 15.0]);
        line_chart(data).title("Sales").color(Color::CYAN)
      render: rust

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives / Prior Art
      description: Other solutions you considered, or similar features in other projects (optional)

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I'm willing to help implement this

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I searched existing issues
          required: true
